#!/bin/bash -ex

echo "Internal release. Not copying to scala-lang.org"
exit 0

# need to re-declare it as an array, not sure how to do that directly in jenkins
declare -a sshCharaArgs="$sshCharaArgs"

if [[ "$version" =~ .*-nightly ]]
then archivesDir="~linuxsoft/archives/scala/nightly/2.11.x"
else archivesDir="~linuxsoft/archives/scala"
fi

echo "Symlinking $archivesDir/api/$version to $archivesDir/api/2.11.x."

ssh "${sshCharaArgs[@]}" "cd $archivesDir/api/ ; [[ -d $version ]] && ln -sfn $version 2.11.x"

# needs to run once on new major release:
# ssh "${sshCharaArgs[@]}" "cd $archivesDir/api/ ; [[ -d $version ]] && ln -sfn 2.11.x current"

